apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
spec:
  selector:
    matchLabels:
      component: broker
  replicas: 1
  template:
    metadata:
      labels:
        component: broker
    spec:
      containers:
        - name: broker
          image: confluentinc/cp-kafka:latest
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-svc.default.svc.cluster.local:2181"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://broker-svc.default.svc.cluster.local:29092,PLAINTEXT_HOST://localhost:9092
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"
            - name: KAFKA_NUM_PARTITIONS
              value: "5"
            - name: KAFKA_JMX_PORT
              value: "9101"
            - name: KAFKA_JMX_HOSTNAME
              value: localhost
          ports:
            - containerPort: 29092
              name: p1
            - containerPort: 9092
              name: p2
            - containerPort: 9101
              name: p3
---
apiVersion: v1
kind: Service
metadata:
  name: broker-svc
spec:
  selector:
    component: broker
  type: ClusterIP
  ports:
    - name: broker
      protocol: TCP
      port: 9092
    - name: broker2
      protocol: TCP
      port: 29092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker2
spec:
  selector:
    matchLabels:
      component: broker2
  replicas: 1
  template:
    metadata:
      labels:
        component: broker2
    spec:
      containers:
        - name: broker2
          image: confluentinc/cp-kafka:latest
          env:
            - name: KAFKA_BROKER_ID
              value: "2"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-svc.default.svc.cluster.local:2181"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://broker2-svc.default.svc.cluster.local:29093,PLAINTEXT_HOST://localhost:9093
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"
            - name: KAFKA_NUM_PARTITIONS
              value: "5"
            - name: KAFKA_JMX_PORT
              value: "9101"
            - name: KAFKA_JMX_HOSTNAME
              value: localhost
          ports:
            - containerPort: 29093
              name: p1
            - containerPort: 9093
              name: p2
            - containerPort: 9101
              name: p3
---
apiVersion: v1
kind: Service
metadata:
  name: broker2-svc
spec:
  selector:
    component: broker2
  type: ClusterIP
  ports:
    - name: broker
      protocol: TCP
      port: 9093
    - name: broker2
      protocol: TCP
      port: 29093
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker3
spec:
  selector:
    matchLabels:
      component: broker3
  replicas: 1
  template:
    metadata:
      labels:
        component: broker3
    spec:
      containers:
        - name: broker3
          image: confluentinc/cp-kafka:latest
          env:
            - name: KAFKA_BROKER_ID
              value: "3"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-svc.default.svc.cluster.local:2181"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://broker3-svc.default.svc.cluster.local:29094,PLAINTEXT_HOST://localhost:9094
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"
            - name: KAFKA_NUM_PARTITIONS
              value: "5"
            - name: KAFKA_JMX_PORT
              value: "9101"
            - name: KAFKA_JMX_HOSTNAME
              value: localhost
          ports:
            - containerPort: 29094
              name: p1
            - containerPort: 9094
              name: p2
            - containerPort: 9101
              name: p3
---
apiVersion: v1
kind: Service
metadata:
  name: broker3-svc
spec:
  selector:
    component: broker3
  type: ClusterIP
  ports:
    - name: broker
      protocol: TCP
      port: 9094
    - name: broker2
      protocol: TCP
      port: 29094
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-api
  labels:
    component: ingestion-api
spec:
  selector:
    matchLabels:
      component: ingestion-api
  replicas: 1
  template:
    metadata:
      labels:
        component: ingestion-api
    spec:
      containers:
        - name: ingestion-api
          image: koukika/kafka-generator:1.1
          ports:
            - containerPort: 3000
              name: api
---
apiVersion: v1
kind: Service
metadata:
  name: ingestion-api-svc
spec:
  selector:
    component: ingestion-api
  type: ClusterIP
  ports:
    - name: ingestion-api
      protocol: TCP
      port: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-api2
  labels:
    component: ingestion-api2
spec:
  selector:
    matchLabels:
      component: ingestion-api2
  replicas: 1
  template:
    metadata:
      labels:
        component: ingestion-api2
    spec:
      containers:
        - name: ingestion-api2
          image: koukika/kafka-generator2:1.1
          ports:
            - containerPort: 3000
              name: api
---
apiVersion: v1
kind: Service
metadata:
  name: ingestion-api2-svc
spec:
  selector:
    component: ingestion-api2
  type: ClusterIP
  ports:
    - name: ingestion-api2
      protocol: TCP
      port: 3000

