kind: Namespace
apiVersion: v1
metadata:
  name: kafka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: kafka
spec:
  selector:
    matchLabels:
      component: zookeeper
  replicas: 1
  template:
    metadata:
      labels:
        component: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:latest
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
          ports:
            - containerPort: 2181
              name: zk
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-svc
  namespace: kafka
spec:
  selector:
    component: zookeeper
  type: ClusterIP
  ports:
    - name: zk
      protocol: TCP
      port: 2181
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
  namespace: kafka
spec:
  selector:
    matchLabels:
      component: broker
  replicas: 1
  template:
    metadata:
      labels:
        component: broker
    spec:
      containers:
        - name: broker
          image: confluentinc/cp-kafka:latest
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-svc.kafka.svc.cluster.local:2181"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://broker-svc.kafka.svc.cluster.local:29092,PLAINTEXT_HOST://localhost:9092
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"
            - name: KAFKA_JMX_PORT
              value: "9101"
            - name: KAFKA_JMX_HOSTNAME
              value: localhost
          ports:
            - containerPort: 29092
              name: p1
            - containerPort: 9092
              name: p2
            - containerPort: 9101
              name: p3
---
apiVersion: v1
kind: Service
metadata:
  name: broker-svc
  namespace: kafka
spec:
  selector:
    component: broker
  type: ClusterIP
  ports:
    - name: broker
      protocol: TCP
      port: 9092
    - name: broker2
      protocol: TCP
      port: 29092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-api
  namespace: kafka
  labels:
    component: ingestion-api
spec:
  selector:
    matchLabels:
      component: ingestion-api
  replicas: 1
  template:
    metadata:
      labels:
        component: ingestion-api
    spec:
      containers:
        - name: ingestion-api
          image: koukika/kafka-generator:latest
          ports:
            - containerPort: 3000
              name: api
---
apiVersion: v1
kind: Service
metadata:
  name: ingestion-api-svc
  namespace: kafka
spec:
  selector:
    component: ingestion-api
  type: ClusterIP
  ports:
    - name: ingestion-api
      protocol: TCP
      port: 3000
