kind: Namespace
apiVersion: v1
metadata:
  name: spark2
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-acc
  namespace: spark2
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: spark2
  name: spark-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: spark2
  name: spark-role-binding
subjects:
  - kind: ServiceAccount
    name: spark-acc
    namespace: spark2
roleRef:
  kind: ClusterRole
  name: spark-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  namespace: spark2
  labels:
    component: spark-master
spec:
  selector:
    matchLabels:
      component: spark-master
  replicas: 1
  template:
    metadata:
      labels:
        component: spark-master
    spec:
      serviceAccountName: spark-acc
      containers:
        - name: spark-master
          image: koukika/spark-master:latest
          ports:
            - containerPort: 7077
              name: master
            - containerPort: 7001
              name: driver
            - containerPort: 4040
              name: webui
            - containerPort: 6066
              name: restserver
            - containerPort: 8080
              name: sparkui
            - containerPort: 7005
              name: blockmanager
          args:
            - master
          env:
            - name: SPARK_CONF_DIR
              value: "/conf"
            - name: MASTER
              value: "spark://spark-master-svc.spark2.svc.cluster.local:7077"
            - name: SPARK_MASTER_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
---
apiVersion: v1
kind: Service
metadata:
  name: spark-master-svc
  namespace: spark2
spec:
  selector:
    component: spark-master
  type: ClusterIP
  ports:
    - name: master
      protocol: TCP
      port: 7077
    - name: webui
      protocol: TCP
      port: 4040
    - name: restserver
      protocol: TCP
      port: 6066
    - name: sparkui
      protocol: TCP
      port: 8080
    - name: driver
      protocol: TCP
      port: 7001
    - name: blockmanager
      protocol: TCP
      port: 7005
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
  namespace: spark2
  labels:
    component: spark-worker
spec:
  selector:
    matchLabels:
      component: spark-worker
  replicas: 1
  template:
    metadata:
      labels:
        component: spark-worker
    spec:
      serviceAccountName: spark-acc
      containers:
        - name: spark-worker
          image: koukika/spark-worker:latest
          ports:
            - containerPort: 8081
              name: webui
          env:
            - name: SPARK_CONF_DIR
              value: "/conf"
            - name: SPARK_WORKER_CORES
              value: "2"
            - name: SPARK_WORKER_MEMORY
              value: "2g"
            - name: SPARK_WORKER_PORT
              value: "8881"
            - name: SPARK_WORKER_WEBUI_PORT
              value: "8081"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver
  namespace: spark2
  labels:
    component: driver
spec:
  selector:
    matchLabels:
      component: driver
  replicas: 1
  template:
    metadata:
      labels:
        component: driver
    spec:
      serviceAccountName: spark-acc
      containers:
        - name: driver
          image: koukika/spark-driver:latest
          ports:
            - containerPort: 7001
              name: driverp
            - containerPort: 4040
              name: webui
            - containerPort: 5003
              name: blockm
          env:
            - name: MASTER
              value: "spark://spark-master-svc.spark2.svc.cluster.local:7077"
---
apiVersion: v1
kind: Service
metadata:
  name: spark-driver-svc
  namespace: spark2
spec:
  selector:
    component: driver
  type: ClusterIP
  ports:
    - name: driverport
      protocol: TCP
      port: 7001
    - name: webui
      protocol: TCP
      port: 4040
    - name: blockm
      protocol: TCP
      port: 5003
